name: iot_control_app
description: A Flutter application for IoT device control
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mqtt_client: ^10.0.0  # For MQTT communication
  flutter_bloc: ^8.1.3  # For state management
  equatable: ^2.0.5    # For value comparison
  connectivity_plus: ^5.0.1  # For network connectivity checking

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.4    # For testing BLoC
  mocktail: ^1.0.1     # For mocking in tests

flutter:
  uses-material-design: true